### ISSUE TITLE
Reduce warning messages to ensure focus on getting docs right

### ISSUE THREAD

**Issue by macite** [splashkit/splashkit-translator#12]
Need to ensure that messages reported should be actioned.
## eg:

Conflicting declarations for function/method (create_animation) outside a
class (apioclass=HeaderDoc::Header).  This is probably not what
you want.  This warning is usually caused by failing to include a
HeaderDoc comment for the enclosing class or by using the wrong name
## with an old-style HeaderDoc tag such as @function.

This should be filtered, so that it is easy to focus on what needs to be done.

**Comment by alexcu** [comment]
Have resolved this on a branch on my fork

**Comment by alexcu** [comment]
Forgot to submit a PR for this—my bad! Check out https://github.com/splashkit/splashkit-translator/pull/14.
