### ISSUE TITLE
Translator should raise errors on unknown attributes

### ISSUE THREAD

**Issue by macite** [splashkit/splashkit-translator#13]
The translator should raise errors when it encounters unknown attributes. This will help identify things like misspelt identifiers etc.

**Comment by alexcu** [comment]
At present only violating attributes (those that violate the rules we have decided upon) are considered here. But agreed—let's narrow down the list of attributes and any unknown ones will throw a parser error. I will submit a PR for this for unknown attributes.

**Comment by alexcu** [comment]
This is fixed in https://github.com/alexcu/splashkit-translator/tree/enhance/error-on-unknown-attribute but this branch is dependent on https://github.com/splashkit/splashkit-translator/pull/14 being merged first.
