### ISSUE TITLE
Warn on non-unique method names

### ISSUE THREAD

**Issue by macite** [splashkit/splashkit-translator#25]
We need to add in checks that each function is unique in the following combinations:

global function name + suffix
method name + suffix (in the class scope)

When a function is not unique, an error should be raised to ensure that languages without overloading are correctly supported.

**Comment by alexcu** [comment]
@macite Are you sure the existing checks aren't already working for this? i.e., https://github.com/splashkit/splashkit-translator/blob/master/src/parser.rb#L563 and https://github.com/splashkit/splashkit-translator/blob/master/src/parser.rb#L522

**Comment by macite** [comment]
Ok I think I see the problem... its only checking if you tried to make it unique. If not then its says its ok... there should always be a unique name. It is just the name if the suffix is not supplied.

**Comment by macite** [comment]
"When suffix is used, the name must be unique to the global namespace." 

Should be 

"All method names must be unique, when overloading supply a suffix to make the method unique within the global and class scopes"

**Comment by alexcu** [comment]
As long as someone has provided a suffix, it checks it, but if someone hasn't then it still needs to be unique.

**Comment by macite** [comment]
Fixed in commit `ad9610c`
