### ISSUE TITLE
No License.

### ISSUE THREAD

**Issue by monoxane** [splashkit/splashkit-translator#42]
This repository is aimed at beginners but does not have a license file in it, a lack of license is legally implicit absolute copyright for all content by its original authors which results in literally everyone forking or cloning this code to be in violation of the copyright law of the US (GitHub and the code location), and Australia (Organization location and presumed majority of the users).

Please rectify this or a number of people will be unable to continue coursework from the university.

**Comment by alexcu** [comment]
Hi @monoxane,

SplashKit is licensed under GPL, stated on [SplashKit.io](https://www.splashkit.io)'s footer:

> Except as otherwise noted, SplashKit is licensed under GPL.

@macite it seems the other repos also are missing an explicit `LICENSE` file.

**Comment by monoxane** [comment]
As per copyright law if there is no license distributed within the source package, the code is not under license, so even though it says GPL-3.0 on the site it doesn't apply to any of the repositories, nor the use of the binaries.

**Comment by alexcu** [comment]
See dd6dd35.

**Comment by monoxane** [comment]
Please also be aware that for the new license to be valid everyone who has contributed code to this (And the other repositories) has to give explicit permission that they are now licensing contributed code under the new GPL-3.0 license, the same as if a repo were to change between different open source licenses.
